package net.viv.moreamethyst.worldgen.geode;

import net.minecraft.tags.BiomeTags;
import net.minecraft.tags.TagKey;
import net.minecraft.world.level.biome.Biome;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.viv.moreamethyst.block.ModBlocks;

import java.util.List;

public class GeodeDataList {

    public record GeodeData(String name, Block inner, Block filler, Block cluster, Block large, Block medium, Block small, Block middle, Block outer, TagKey<Biome> targetBiomes) {}

    public static final List<GeodeData> GEODE_DATA_LIST = List.of(
            new GeodeData ("red",
                    ModBlocks.AMETHYST_BLOCK_RED.get(),
                    ModBlocks.BUDDING_AMETHYST_RED.get(),
                    ModBlocks.AMETHYST_CLUSTER_RED.get(),
                    ModBlocks.LARGE_AMETHYST_BUD_RED.get(),
                    ModBlocks.MEDIUM_AMETHYST_BUD_RED.get(),
                    ModBlocks.SMALL_AMETHYST_BUD_RED.get(),
                    Blocks.CALCITE,
                    Blocks.SMOOTH_BASALT,
                    BiomeTags.IS_OVERWORLD),

            new GeodeData ("orange",
                    ModBlocks.AMETHYST_BLOCK_ORANGE.get(),
                    ModBlocks.BUDDING_AMETHYST_ORANGE.get(),
                    ModBlocks.AMETHYST_CLUSTER_ORANGE.get(),
                    ModBlocks.LARGE_AMETHYST_BUD_ORANGE.get(),
                    ModBlocks.MEDIUM_AMETHYST_BUD_ORANGE.get(),
                    ModBlocks.SMALL_AMETHYST_BUD_ORANGE.get(),
                    Blocks.CALCITE,
                    Blocks.SMOOTH_BASALT,
                    BiomeTags.IS_OVERWORLD),

            new GeodeData ("yellow",
                    ModBlocks.AMETHYST_BLOCK_YELLOW.get(),
                    ModBlocks.BUDDING_AMETHYST_YELLOW.get(),
                    ModBlocks.AMETHYST_CLUSTER_YELLOW.get(),
                    ModBlocks.LARGE_AMETHYST_BUD_YELLOW.get(),
                    ModBlocks.MEDIUM_AMETHYST_BUD_YELLOW.get(),
                    ModBlocks.SMALL_AMETHYST_BUD_YELLOW.get(),
                    Blocks.CALCITE,
                    Blocks.SMOOTH_BASALT,
                    BiomeTags.IS_OVERWORLD),

            new GeodeData ("lime",
                    ModBlocks.AMETHYST_BLOCK_LIME.get(),
                    ModBlocks.BUDDING_AMETHYST_LIME.get(),
                    ModBlocks.AMETHYST_CLUSTER_LIME.get(),
                    ModBlocks.LARGE_AMETHYST_BUD_LIME.get(),
                    ModBlocks.MEDIUM_AMETHYST_BUD_LIME.get(),
                    ModBlocks.SMALL_AMETHYST_BUD_LIME.get(),
                    Blocks.CALCITE,
                    Blocks.SMOOTH_BASALT,
                    BiomeTags.IS_OVERWORLD),

            new GeodeData ("green",
                    ModBlocks.AMETHYST_BLOCK_GREEN.get(),
                    ModBlocks.BUDDING_AMETHYST_GREEN.get(),
                    ModBlocks.AMETHYST_CLUSTER_GREEN.get(),
                    ModBlocks.LARGE_AMETHYST_BUD_GREEN.get(),
                    ModBlocks.MEDIUM_AMETHYST_BUD_GREEN.get(),
                    ModBlocks.SMALL_AMETHYST_BUD_GREEN.get(),
                    Blocks.CALCITE,
                    Blocks.SMOOTH_BASALT,
                    BiomeTags.IS_OVERWORLD),

            new GeodeData ("cyan",
                    ModBlocks.AMETHYST_BLOCK_CYAN.get(),
                    ModBlocks.BUDDING_AMETHYST_CYAN.get(),
                    ModBlocks.AMETHYST_CLUSTER_CYAN.get(),
                    ModBlocks.LARGE_AMETHYST_BUD_CYAN.get(),
                    ModBlocks.MEDIUM_AMETHYST_BUD_CYAN.get(),
                    ModBlocks.SMALL_AMETHYST_BUD_CYAN.get(),
                    Blocks.CALCITE,
                    Blocks.SMOOTH_BASALT,
                    BiomeTags.IS_OVERWORLD),

            new GeodeData ("light_blue",
                    ModBlocks.AMETHYST_BLOCK_LIGHT_BLUE.get(),
                    ModBlocks.BUDDING_AMETHYST_LIGHT_BLUE.get(),
                    ModBlocks.AMETHYST_CLUSTER_LIGHT_BLUE.get(),
                    ModBlocks.LARGE_AMETHYST_BUD_LIGHT_BLUE.get(),
                    ModBlocks.MEDIUM_AMETHYST_BUD_LIGHT_BLUE.get(),
                    ModBlocks.SMALL_AMETHYST_BUD_LIGHT_BLUE.get(),
                    Blocks.CALCITE,
                    Blocks.SMOOTH_BASALT,
                    BiomeTags.IS_OVERWORLD),

            new GeodeData ("blue",
                    ModBlocks.AMETHYST_BLOCK_BLUE.get(),
                    ModBlocks.BUDDING_AMETHYST_BLUE.get(),
                    ModBlocks.AMETHYST_CLUSTER_BLUE.get(),
                    ModBlocks.LARGE_AMETHYST_BUD_BLUE.get(),
                    ModBlocks.MEDIUM_AMETHYST_BUD_BLUE.get(),
                    ModBlocks.SMALL_AMETHYST_BUD_BLUE.get(),
                    Blocks.CALCITE,
                    Blocks.SMOOTH_BASALT,
                    BiomeTags.IS_OVERWORLD),

            new GeodeData ("magenta",
                    ModBlocks.AMETHYST_BLOCK_MAGENTA.get(),
                    ModBlocks.BUDDING_AMETHYST_MAGENTA.get(),
                    ModBlocks.AMETHYST_CLUSTER_MAGENTA.get(),
                    ModBlocks.LARGE_AMETHYST_BUD_MAGENTA.get(),
                    ModBlocks.MEDIUM_AMETHYST_BUD_MAGENTA.get(),
                    ModBlocks.SMALL_AMETHYST_BUD_MAGENTA.get(),
                    Blocks.CALCITE,
                    Blocks.SMOOTH_BASALT,
                    BiomeTags.IS_OVERWORLD),

            new GeodeData ("pink",
                    ModBlocks.AMETHYST_BLOCK_PINK.get(),
                    ModBlocks.BUDDING_AMETHYST_PINK.get(),
                    ModBlocks.AMETHYST_CLUSTER_PINK.get(),
                    ModBlocks.LARGE_AMETHYST_BUD_PINK.get(),
                    ModBlocks.MEDIUM_AMETHYST_BUD_PINK.get(),
                    ModBlocks.SMALL_AMETHYST_BUD_PINK.get(),
                    Blocks.CALCITE,
                    Blocks.SMOOTH_BASALT,
                    BiomeTags.IS_OVERWORLD),

            new GeodeData ("white",
                    ModBlocks.AMETHYST_BLOCK_WHITE.get(),
                    ModBlocks.BUDDING_AMETHYST_WHITE.get(),
                    ModBlocks.AMETHYST_CLUSTER_WHITE.get(),
                    ModBlocks.LARGE_AMETHYST_BUD_WHITE.get(),
                    ModBlocks.MEDIUM_AMETHYST_BUD_WHITE.get(),
                    ModBlocks.SMALL_AMETHYST_BUD_WHITE.get(),
                    Blocks.CALCITE,
                    Blocks.SMOOTH_BASALT,
                    BiomeTags.IS_OVERWORLD),

            new GeodeData ("light_gray",
                    ModBlocks.AMETHYST_BLOCK_LIGHT_GRAY.get(),
                    ModBlocks.BUDDING_AMETHYST_LIGHT_GRAY.get(),
                    ModBlocks.AMETHYST_CLUSTER_LIGHT_GRAY.get(),
                    ModBlocks.LARGE_AMETHYST_BUD_LIGHT_GRAY.get(),
                    ModBlocks.MEDIUM_AMETHYST_BUD_LIGHT_GRAY.get(),
                    ModBlocks.SMALL_AMETHYST_BUD_LIGHT_GRAY.get(),
                    Blocks.CALCITE,
                    Blocks.SMOOTH_BASALT,
                    BiomeTags.IS_OVERWORLD),

            new GeodeData ("gray",
                    ModBlocks.AMETHYST_BLOCK_GRAY.get(),
                    ModBlocks.BUDDING_AMETHYST_GRAY.get(),
                    ModBlocks.AMETHYST_CLUSTER_GRAY.get(),
                    ModBlocks.LARGE_AMETHYST_BUD_GRAY.get(),
                    ModBlocks.MEDIUM_AMETHYST_BUD_GRAY.get(),
                    ModBlocks.SMALL_AMETHYST_BUD_GRAY.get(),
                    Blocks.CALCITE,
                    Blocks.SMOOTH_BASALT,
                    BiomeTags.IS_OVERWORLD),

            new GeodeData ("black",
                    ModBlocks.AMETHYST_BLOCK_BLACK.get(),
                    ModBlocks.BUDDING_AMETHYST_BLACK.get(),
                    ModBlocks.AMETHYST_CLUSTER_BLACK.get(),
                    ModBlocks.LARGE_AMETHYST_BUD_BLACK.get(),
                    ModBlocks.MEDIUM_AMETHYST_BUD_BLACK.get(),
                    ModBlocks.SMALL_AMETHYST_BUD_BLACK.get(),
                    Blocks.CALCITE,
                    Blocks.SMOOTH_BASALT,
                    BiomeTags.IS_OVERWORLD),

            new GeodeData ("brown",
                    ModBlocks.AMETHYST_BLOCK_BROWN.get(),
                    ModBlocks.BUDDING_AMETHYST_BROWN.get(),
                    ModBlocks.AMETHYST_CLUSTER_BROWN.get(),
                    ModBlocks.LARGE_AMETHYST_BUD_BROWN.get(),
                    ModBlocks.MEDIUM_AMETHYST_BUD_BROWN.get(),
                    ModBlocks.SMALL_AMETHYST_BUD_BROWN.get(),
                    Blocks.CALCITE,
                    Blocks.SMOOTH_BASALT,
                    BiomeTags.IS_OVERWORLD)


    );
}
